const video=document.getElementById('video'),startBtn=document.getElementById('startBtn'),shotBtn=document.getElementById('shotBtn'),cameraView=document.getElementById('cameraView'),result=document.getElementById('result'),canvas=document.getElementById('canvas'),downloadBtn=document.getElementById('downloadBtn'),againBtn=document.getElementById('againBtn');let stream=null;
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1920}},audio:false});video.srcObject=stream;await video.play();startBtn.classList.add('hidden');shotBtn.disabled=false}catch(e){alert('No se pudo abrir la cámara. Permití el acceso e intentá nuevamente.')}}
function rr(c,x,y,w,h,r,fill){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill()}
function drawUniform(c,w,h){const cx=w/2; c.save();
let cw=w*.96,ch=h*.56,top=h*.46,x=(w-cw)/2;c.fillStyle='#4d565b';c.beginPath();c.moveTo(x+cw*.18,top);c.lineTo(x+cw*.36,top+ch*.06);c.lineTo(x+cw*.42,top+ch*.15);c.lineTo(x+cw*.58,top+ch*.15);c.lineTo(x+cw*.64,top+ch*.06);c.lineTo(x+cw*.82,top);c.lineTo(x+cw,top+ch*.17);c.lineTo(x+cw*.92,top+ch);c.lineTo(x+cw*.08,top+ch);c.lineTo(x,top+ch*.17);c.closePath();c.fill();
c.strokeStyle='#d7b34e';c.lineWidth=Math.max(5,w*.008);c.beginPath();c.moveTo(x+cw*.13,top+ch*.08);c.lineTo(x+cw*.30,top+ch*.10);c.moveTo(x+cw*.70,top+ch*.10);c.lineTo(x+cw*.87,top+ch*.08);c.stroke();
c.fillStyle='#151819';c.beginPath();c.moveTo(cx-w*.20,h*.42);c.lineTo(cx-w*.02,h*.54);c.lineTo(cx,h*.48);c.lineTo(cx+w*.02,h*.54);c.lineTo(cx+w*.20,h*.42);c.lineTo(cx+w*.14,h*.51);c.lineTo(cx,h*.58);c.lineTo(cx-w*.14,h*.51);c.closePath();c.fill();c.strokeStyle='#d7b34e';c.lineWidth=4;c.stroke();
c.fillStyle='#e1bc52';c.font=Math.round(w*.055)+'px sans-serif';c.fillText('★',cx+w*.20,h*.62);c.font=Math.round(w*.028)+'px sans-serif';c.fillText('✦ ✦',cx-w*.34,h*.51);c.fillText('✦ ✦',cx+w*.23,h*.51);
for(let i=0;i<3;i++){c.beginPath();c.arc(cx,h*(.60+i*.09),w*.018,0,Math.PI*2);c.fill()}
let capW=w*.50,capH=h*.17,capX=cx-capW/2,capY=h*.07;rr(c,capX,capY,capW,capH,capH*.42,'#e5e5e5');c.fillStyle='#17191b';c.fillRect(capX+capW*.08,capY+capH*.52,capW*.84,capH*.18);c.fillStyle='#d7b34e';c.fillRect(capX+capW*.12,capY+capH*.69,capW*.76,Math.max(5,h*.008));c.beginPath();c.ellipse(cx,capY+capH*.91,capW*.32,capH*.13,0,0,Math.PI*2);c.fillStyle='#141617';c.fill();c.font=Math.round(w*.07)+'px sans-serif';c.fillStyle='#d7b34e';c.textAlign='center';c.fillText('☀',cx,capY+capH*.42);c.restore()}
function takePhoto(){const w=video.videoWidth,h=video.videoHeight;if(!w||!h)return;canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.drawImage(video,0,0,w,h);drawUniform(c,w,h);downloadBtn.href=canvas.toDataURL('image/jpeg',.92);cameraView.classList.add('hidden');shotBtn.classList.add('hidden');result.classList.remove('hidden')}
function again(){result.classList.add('hidden');cameraView.classList.remove('hidden');shotBtn.classList.remove('hidden')}
startBtn.addEventListener('click',startCamera);shotBtn.addEventListener('click',takePhoto);againBtn.addEventListener('click',again);